### ISSUE TITLE
Hiding 'Debug AHK Script' Button

### ISSUE THREAD

**Issue by nmpsyntax** [mark-wiemer/vscode-autohotkey-plus-plus#10]
Could we get the ability to hide the 'Debug AHK Script' button that sits to the right of the tabs? I linked a picture for reference.

![Debug AHK Script Button](https://user-images.githubusercontent.com/57739599/100100384-b8e01a80-2e2e-11eb-910c-23e50b33e1cd.PNG)

**Comment by mark-wiemer** [comment]
Sure, I can look into that this weekend 👍

**Comment by mark-wiemer** [comment]
Sorry, I didn't manage to get around to this. I'm swamped through Dec 25, I will find some time after that. I won't put this on the Dec 2020 milestone as I need to fix bugs before I add features, but anyone is welcome to open a PR for this :)

**Comment by mark-wiemer** [comment]
This is determined in [package.json](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/56eb22c413f6800b58f1a271ebead981e5497599/package.json#L177-L183), but it doesn't look like there's much flexibility in the `when` condition (see [VS Code Contribution Points: Menus](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)). This will probably be backlogged for a while as it is a minor change.

**Comment by fade2gray** [comment]
Chen is/was considering dropping support for the built-in debugger. Is it necessary to include a debugger when there are dedicated extensions available?

**Comment by ElectroLund** [comment]
Just curious, why would you want to hide the debug play button?

**Comment by fade2gray** [comment]
@mark-wiemer https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/10#issuecomment-762830623 ?

**Comment by mark-wiemer** [comment]
@fade2gray No, it's not necessary to maintain. But maintenance cost is low right now, I am unaware of any bugs or potential QoL improvements. It's useful to keep in this extension, for those that make simpler scripts and don't want to depend on other extensions.

**Comment by mark-wiemer** [comment]
This will be a setting in the next release, likely this weekend :) Default behavior will still show the debug button.

**Comment by nmpsyntax** [comment]
Sweet, thanks Mark. I hope I didn't send you too far down the rabbit hole,
maybe just far enough to learn something? Thanks for sticking with the
issue.

**Comment by mark-wiemer** [comment]
Yep, I definitely learned something! The `when` condition is much more flexible than I thought, and this knowledge will be helpful fixing future issues. Thanks for the request 🙂
