### ISSUE TITLE
[Enhancement] Change the "Debug" icon to align with the default VSCode menu item icon design

### ISSUE THREAD

**Issue by wenfangdu** [mark-wiemer/vscode-autohotkey-plus-plus#100]
The current "Debug" icon looks blurry and inconsistent with the default VSCode menu item icon design:

![image](https://user-images.githubusercontent.com/28700378/130889993-a382dbcb-f682-40ab-8641-f4f196e31eb9.png)

Compared to [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner)'s "Run Code" icon (crisp and consistent with the VSCode icon design):

![image](https://user-images.githubusercontent.com/28700378/130889265-d5032ca1-5131-41d0-ad73-a5a53e873427.png)

Would be great to make it crisper and align with the default VSCode menu item icon design.

P.S. I'm not suggesting AHK++ should use Code Runner's icon.

**Comment by mark-wiemer** [comment]
See #102 as well

**Comment by mark-wiemer** [comment]
See also https://code.visualstudio.com/api/references/icons-in-labels for some sample icons provided by VS Code

**Comment by mark-wiemer** [comment]
Ah, much better. Now using the default debug-alt

![image](https://user-images.githubusercontent.com/7833360/177266198-e5d82610-0347-468b-998c-faa66148026d.png)
