### ISSUE TITLE
[Bug] `ahk++.run` conflicts with `ahk++.runSelection`

### ISSUE THREAD

**Issue by wenfangdu** [mark-wiemer/vscode-autohotkey-plus-plus#101]
Repro Steps:

When setting both `ahk++.run` and `ahk++.runSelection` to the same shortcut, `ahk++.runSelection` has higher precedence than `ahk++.run`.

Solution 1:

When there's no selection in the editor, run `ahk++.run`, otherwise run `ahk++.runSelection`.

Solution 2:

Add `ahk++.ignoreSelection` setting (defaults to `false`), remove `ahk++.runSelection` command.

**Comment by mark-wiemer** [comment]
Because AHK++ isn't fully in charge of keyboard shortcuts, and because there's an easy, well-described workaround, I'm closing this issue. Thanks for the help @fade2gray and for documenting your solution @wenfangdu
