### ISSUE TITLE
Regarding issue/enhancement #100

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer/vscode-autohotkey-plus-plus#102]
@wenfangdu (It appears you have decided to block my comments)

Regarding Code Runner's icon and the AutoHotkey Plus Plus debugger icon:

Code Runner's icon appears when any Plain Text or any script editor has focus, but when an AHK++ editor has focus, both icons are displayed unless the option to not display the AHK++ icon has been chosen.

![debug-icon-2](https://user-images.githubusercontent.com/1332009/130979619-4b92dcfe-029f-4a74-97ca-0a046f5a65ba.png)

Note: replaced non working vid with working vid.

https://user-images.githubusercontent.com/1332009/130983675-a6fa2037-031b-4f6d-ada0-4d5208037cc2.mp4

**Comment by mark-wiemer** [comment]
Closing as duplicate / non-issue, not sure why @fade2gray was unable to comment on the other issue :/
