### ISSUE TITLE
Ahk v2 snippets - is it possible to be able to switch snippets in the setting V1 - V2

### ISSUE THREAD

**Issue by dmtr99** [mark-wiemer/vscode-autohotkey-plus-plus#106]
I have create an updates snippet file for ahk V2 with the intention to just be used for V2.
Is it possible to switch between the snippet files?
If it is possible, it would also be nice to be able to switch also to another syntax file for v2. where old variables and functions are made bold red or striped, and new ones are added. The quotes are also changed in V2, not sure if it is easy to include this.

https://github.com/dmtr99/AHK-V2-Syntax-Visual-Studio-Code/blob/main/ah2.code-snippets

**Comment by mark-wiemer** [comment]
I appreciate the effort. Unfortunately I will be focusing on supporting AHK v1 until there is a clear roadmap for the official release of v2. While in beta, anything could change about v2 in theory, and I need to build a solid framework with a stable language before branching out. Sorry for the inconvenience :/

Closing as out-of-scope for this project for now.

**Comment by mark-wiemer** [comment]
The v2 beta is encouraging, but the solid framework is most important.
