### ISSUE TITLE
Debug Console should evaluate expressions

### ISSUE THREAD

**Issue by davaya** [mark-wiemer/vscode-autohotkey-plus-plus#107]
**Is your feature request related to a problem? Please describe.**

The debug console will display variable values when given a name, but displays null when given an expression.  Variable values are already visible in the variables window.  Expressions are not displayed in the variables window, so it would be helpful to display them in the debugger.

![ptr-debug](https://user-images.githubusercontent.com/19152940/133008405-a2c8fb81-e138-4741-a82f-3a8c417c3ffd.jpg)

**Describe the solution you'd like**
After typing 1 + 2, the console displays 3.

**Describe alternatives you've considered**
None

**Additional context**
When a variable contains a pointer, it is impossible to view the referenced content.  For example, the AHK tutorial https://www.autohotkey.com/docs/commands/DllCall.htm#ExStruct returns a pointer to a Rect, but the debug console cannot display the value of the Rect.

P.S., this is already an absolutely awesome extension; please take issues as kudos, not criticism.

**Comment by mark-wiemer** [comment]
Honestly, this would be a great feature. But I have no idea how to implement it yet 😁 I'd suggest [vscode-autohotkey-debug](https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug) in the meantime

**Comment by Lexikos** [comment]
Eval requires support from the debugger backend (in AutoHotkey); that support currently doesn't exist.

**Comment by mark-wiemer** [comment]
Makes sense. I'll be closing this one as out of scope for now, once this support is added to AutoHotkey we can reconsider.
