### ISSUE TITLE
While hovering on a keyword show link to the respective AHK documentation webpage.

### ISSUE THREAD

**Issue by anandinasu** [mark-wiemer/vscode-autohotkey-plus-plus#111]
Thanks a lot for your extension. It has helped me a lot :)

I am not sure whether this is possible, Along with the documentation which is shown when you hover the mouse over the keyword,  is it possible to add a link to the respective AHK documentation website. 

Eg: When you hover over the keyword ```MouseGetPos```, along with showing the syntax and explanation, add this link "https://www.autohotkey.com/docs/commands/MouseGetPos.htm" to the tooltip.

**Comment by fade2gray** [comment]
See https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/78

**Comment by anandinasu** [comment]
That is great. Thank You. It is working perfectly fine.
