### ISSUE TITLE
Semi-colon in string in parentheses formats wrong

### ISSUE THREAD

**Issue by dldmlwnd** [mark-wiemer/vscode-autohotkey-plus-plus#119]
### Description

indent happens where it shouldn't
semicolon in string inside parenthesis
triggers indent on next line

### Unformatted input snippet

sql:=strrplace("asd;",";","")
return

### Expected formatted output snippet

sql:=strrplace("asd;",";","")
return

### Actual formatted output snippet

sql:=strrplace("asd;",";","")
  return

**Comment by fade2gray** [comment]
All three example look exactly the same, try using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your comment.

```ahk
sql:=strrplace("asd;",";","")
return
```

**Comment by dldmlwnd** [comment]
Unformatted input snippet
```
sql:=strrplace("asd;",";","")
return
```
Expected formatted output snippet
```
sql:=strrplace("asd;",";","")
return
```
Actual formatted output snippet
```
sql:=strrplace("asd;",";","")
  return
```
Wonder if it shows right.. now

**Comment by fade2gray** [comment]
Confirmed AHK++ v2.8.1, I think @mark-wiemer has other commitments at the moment, so it could be a while before being dealt with.
