### ISSUE TITLE
Does not work if AHK is not installed on the default drive (C:)

### ISSUE THREAD

**Issue by OVERKILL27** [mark-wiemer/vscode-autohotkey-plus-plus#120]
I have AHK installed on my `D:` drive but it seems like this extension only works if AHK is installed on the `C:` drive.

When I try to debug an AHK script with AutoHotkey Plus Plus I get the following output:
`AutoHotkey execute bin not found: C:/Program Files/AutoHotkey/AutoHotkeyU64.exe`

Also, when I use the help shortcut `Ctrl + F1` I get a dialogue box popup with the message _"Cannot open the file: C:/Program Files/AutoHotKey/AutoHotKey.chm."_:
![Screenshot 2022-04-26 213854](https://user-images.githubusercontent.com/8603399/165292923-8ffa38ea-2f24-47f6-adeb-a35a69470f83.png)

Could the ability to configure this extension to look in a location other than the default please be added? :)

**Comment by fade2gray** [comment]
![AHK++Settings](https://user-images.githubusercontent.com/1332009/165307525-188a1912-021d-44ab-b108-d51f1b38cfb6.PNG)

**Comment by mark-wiemer** [comment]
Hi @OVERKILL27 , I believe @fade2gray provided great instructions here. Thanks! I'm going to close this -- please re-open if you are still having issues.
