### ISSUE TITLE
Debugger bug introduced with v2.8.3

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer/vscode-autohotkey-plus-plus#153]
I initially discovered the problem when debugging a script using `Step Into (F11)` and encountering a `FileDelete` command. Making sure the said file hadn't somehow become read-only, and that it wasn't open in some other app, I reverted to v2.8.2 which resolved the problem.

The attached video better explains what was happening (I hope) pre and post v2.8.2.

Video starts with v2.8.2 before updating to v2.8.3.

https://user-images.githubusercontent.com/1332009/177618760-ebcaeccd-ec59-4ee9-b749-80110c994690.mp4

**Comment by mark-wiemer** [comment]
:( 2.8.4 will be identical to 2.8.2, I guess. See https://github.com/microsoft/vsmarketplace/issues/235

**Comment by mark-wiemer** [comment]
My mistake, I introduced some "refactors" to clean up the code, but they seem to have broken the debugger and maybe other features. Very sorry for this, I did some testing but obviously missed this somehow. See https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/pull/135. I will revert the changes, publish 2.8.4, and then investigate.

**Comment by mark-wiemer** [comment]
Introduced by #135

**Comment by mark-wiemer** [comment]
Definitely introduced by 0f9d15f `Add ESLint and fix problems`. I've restored the offending branch for investigation.

**Comment by mark-wiemer** [comment]
Trying to write a test to automatically detect this failure. I'll need to programmatically create a breakpoint. I found the command ID for this via searching the command label in keyboard shortcuts, then I found its only reference in the code here: [editor.debug.action.conditionalBreakpoint](https://github.com/microsoft/vscode/blob/0ea37090ffd2eda4d5e18b0d4aef146570d262c2/src/vs/workbench/contrib/debug/browser/debugEditorActions.ts#L73)

**Comment by mark-wiemer** [comment]
`vscode.debug.addBreakpoints` doesn't work as one might expect, it seems to be used internally by a debugger, not by VS Code itself. Sticking with `conditionalBreakpoint` for now.

**Comment by mark-wiemer** [comment]
Identified the root cause: `src/debugger/struct/command.ts#Continue must have value `step_into`, it does not accept `stepinto`. This is probably documented somewhere, but I can't find it :/
