### ISSUE TITLE
Prettier not format file on save

### ISSUE THREAD

**Issue by kyklish** [mark-wiemer/vscode-autohotkey-plus-plus#165]
## Description

`prettier` not format file on save. Need do it outside via cmd :(
Commit not pass if file not properly formatted.

## Expected behavior

Automatically format file by `prettier`

**Comment by mark-wiemer** [comment]
You can edit this in your local clone by editing `editor.formatOnSave` in your Workspace settings:

![image](https://user-images.githubusercontent.com/7833360/179443914-f2b90caa-d496-40cb-b782-951a779e82b1.png)

I don't want to be too opinionated, so I don't want to commit the `settings.json` file.

Closing as out-of-scope

**Comment by kyklish** [comment]
But how about manual formatting? I use default hotkey `Alt+Shift+F` to format before save, but VS Code use built-in formatter for TypeScript, I don't see `Prettier` for available option in list of installed formatters.

**Comment by mark-wiemer** [comment]
Yep! See [language-specific editor settings](https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings)

```jsonc
// settings.json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[ahk]": {
    "editor.defaultFormatter": "mark-wiemer.vscode-autohotkey-plus-plus"
  }
}
```

**Comment by kyklish** [comment]
My bad :/, `Prettier` extension was not installed. Now all works fine.
