### ISSUE TITLE
Comments placed at end of line shifting left

### ISSUE THREAD

**Issue by Cirieno** [mark-wiemer/vscode-autohotkey-plus-plus#187]
I often add a comment at the end of a line with four spaces before the semi-colon, and I'm finding that the formatter is concatenating the spaces into a single space.

### Unformatted input

```
#noEnv    ;// prevents empty variables from being looked up
drawMenuItem__exit()    ;// call this function
```

### Actual formatted output

```
#noEnv ;// prevents empty variables from being looked up
drawMenuItem__exit() ;// call this function
```

**Comment by kyklish** [comment]
This issue is relevant with #94. I have plans to resolve it in near future.
