### ISSUE TITLE
What is a difference between AutoHotkey++ and AutoHotkey-Plus?

### ISSUE THREAD

**Issue by iamkarlson** [mark-wiemer/vscode-autohotkey-plus-plus#19]
Hi, 
I'm struggling to understand what is a real difference between your fork and the previous extension. Could you please elaborate a little?

**Comment by fade2gray** [comment]
One thing, Chen is considering no longer maintaining Plus, but Mark is considering merging it with ++ and, hopefully, keeping it regularly maintained.

**Comment by iamkarlson** [comment]
Does it make any difference for users? I mean the real difference not like "somebody" plans to do something.

**Comment by FuPeiJiang** [comment]
at this very moment, I don't think so,
if you want difference immediately, you can look at my fork, 
I'll be pull requesting to this repo, I already made a pull request, but I got stuck.

**Comment by mark-wiemer** [comment]
Hi @iamkarlson: no, there are no differences yet. I am the "somebody" that plans to do something, but November and December were very hectic months for me leading up to a major work deadline. Now that that's over, I plan to take in all of the changes that are made to AHK Plus, as well as additional changes and bugfixes the community has been recommending but AHK Plus has not implemented. It is up to you which extension you want to use: I recommend keeping your eye on both and choosing the one with a better development lifecycle. Ideally, there would only be one extension: I am working with `cweijan` on this.
