### ISSUE TITLE
Add option to invoke the compiler GUI from the context menu

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer/vscode-autohotkey-plus-plus#243]
Would it be possible to add an option to invoke the compiler GUI from the context menu?

**Comment by mark-wiemer** [comment]
Honestly, I don't use AHK itself at all, so I've never used the compiler GUI 😕 is there any similar behavior in AHK+? Otherwise I'm happy to consider it. It'd be great if you could link some documentation for me so I have a bit more context on exactly what we're looking for

**Comment by fade2gray** [comment]
Well, to invoke the AHK2Exe compile using an AHK script would simply be something like...
```AHK
Run, "C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe"
```

![AHK_settings_ahk2exe](https://user-images.githubusercontent.com/1332009/193470018-51aa8912-46a6-499a-b570-1db0a7fc7123.PNG)

Of course, we can simply do this from Windows explorer, but I thought, hey, this would make things a bit simpler.

![AHK_compile_gui3](https://user-images.githubusercontent.com/1332009/193470064-f6d4e9ce-17a4-4515-9d53-38afec018cdd.PNG)

**Comment by kyklish** [comment]
It's possible:

1. Get active file: `vscode.window.activeTextEditor.document.uri.fsPath`
2. Launch compiler GUI: `Ahk2Exe.exe /gui /in "activeFile"`

From where to execute?

1. Context menu.
2. Command pallet (user can assign hotkey).
3. Both?

@mark-wiemer what do you think?

**Comment by kyklish** [comment]
It's possible. We have `RunnerService.compile()`, it executes `Ahk2Exe.exe /in "inFile" /out "outFile"`. We need add optional key `/gui` to force launch GUI instead of compiling: `... /gui /in ... /out ...`.

From where to execute?

1. Context menu.
2. Command pallet (user can assign hotkey).
3. Both?

@mark-wiemer what do you think?

**Comment by mark-wiemer** [comment]
If possible, both is always best :) we should build in a way that it's easy to integrate both. If for some reason we're limited to only one, command palette is more customizable and accessible with hotkeys.
