### ISSUE TITLE
InStr() function missing parameters

### ISSUE THREAD

**Issue by xzeroun** [mark-wiemer/vscode-autohotkey-plus-plus#263]
## Description

When using InStr() function as the AHK documentation suggests, the AHK++ extension seems to have missed a parameter that is important to my code which is the occurrence parameter.

AHK Docs: InStr(Haystack, Needle , CaseSensitive := false, StartingPos := 1, Occurrence := 1)
AHK++  : InStr(Haystack, Needle [, CaseSensitive?, StartingPos])

## Reproduction steps 

Use AHK++ and try to set an occurrence parameter. Example code given below:

File = "C:\Test\Test\Test.txt"
var := StrSplit(File, "backslash")
MsgBox % var.count()
pos := InStr(File, "backslash",False, 1, var.count())
MsgBox % pos

## Expected behavior

It should provide the character position in a string based on the var.count() result, which would be the last "\" within the string's name.

**Comment by fade2gray** [comment]
`InStr(Haystack, Needle [, CaseSensitive?, StartingPos])` requires a maximum of 4 parameters, and you are providing 5.

Try, `pos := InStr(File, "", , var.count())`.

**Comment by xzeroun** [comment]
Maybe I didn't make it clear enough. The basic InStr function from AHK uses 5 parameters. I need that 5th parameter for occurrence. StrSplit only provides me a way to get the last backslash in a file path, not the position of that backslash within the string. So it tells me there are X amount of backslashes which I want to use var.count() because it gives me the last occurrence. Then I use InStr(File, "backslash", False, 1, var.count()) to get the position of that character. 

My primary issue is that Ahk++ doesn't have the 5th parameter that AHK has by default. Does that make more sense?

**Comment by fade2gray** [comment]
You have your `position` and `occurrence` parameters interposed.

`pos := InStr(File, "",,var.count(), 1)`

See example [#3](https://www.autohotkey.com/docs/commands/InStr.htm#ExCaseSens).

**Comment by xzeroun** [comment]
InStr(Haystack, Needle , CaseSensitive := false, StartingPos := 1, Occurrence := 1) ????

**Comment by fade2gray** [comment]
**You have your start position and occurrence parameters in the wrong positions.**

```ahk
File = "C:\Test\Test\Test.txt"
var := StrSplit(File, "\")
MsgBox % var.count()
pos := InStr(File, "\",False, var.count(), 1)
MsgBox % pos
```

**Comment by fade2gray** [comment]
Scrap that.
Try, `pos := InStr(File, "\",,1, var.count()-1)`

`var.count()` gives you the number of strings that `File` is split into, not the number of backslashes.

**Comment by xzeroun** [comment]
Ahh... that was it the -1, well darn. I do believe the tab complete parameters in InStr() should be updated to include occurrence as of right now it only shows:

InStr(Haystack, Needle [, CaseSensitive?, StartingPos])

Which is not all of the parameters. Was a simple oversight on my end, oh well ty!
