### ISSUE TITLE
Document Format - Switch/Case Statements - Invalid Indentation

### ISSUE THREAD

**Issue by BloodyRnar** [mark-wiemer/vscode-autohotkey-plus-plus#28]
**Describe the bug**

The result of using Format Document when code reaches a Switch statement is incorrect/badly formatted.

**To Reproduce**

Create Code Block in file.
Use Right Click -> Format Document

```

    GetClickType() {
        k := This.keyType
        Switch k {
        Case "RButton":
        return "right"
    Case "LButton":
    return "left"
Case "MButton":
return "mid"
Default:
return This.key
}
}


```
**Expected behavior**

    GetClickType() {
        k := This.keyType
        Switch k {
        Case "RButton":
            return "right"
        Case "LButton":
            return "left"
        Case "MButton":
            return "mid"
        Default:
            return This.key
        }
    }

**Additional context**

Add any other context about the problem here, including screenshots. If no context is needed, please remove this section.
![image](https://user-images.githubusercontent.com/19176329/104989514-3dd75280-59e0-11eb-80a0-7cead83726a8.png)

![image](https://user-images.githubusercontent.com/19176329/104989540-4cbe0500-59e0-11eb-8b3c-72e013955493.png)

**Comment by BloodyRnar** [comment]
Seems related to use of Return keyword.

Workaround:

`    GetClickType() {
        k := This.keyType

        s := This.key

        Switch k {
            Case "RButton":
                s := "right"
            Case "LButton":
                s := "left"
            Case "MButton":
                s := "mid"
            Default:
                s := This.key
        }
        Return, s
    }
`

**Comment by mark-wiemer** [comment]
Unfortunately, due to the complexity of switch-case statements, this isn't an easy fix. It's not easy to determine with certainty when the code is inside or outside of a switch-case block when scanning line by line (the current implementation scans line by line). The best approach would be to implement a full-fledged parser, but that will take some time. Moving this issue to the backlog for now.

And you're right, the current approach to de-indent `return` is what's causing (most of) this issue.

**Comment by mark-wiemer** [comment]
As a side note, you can use three backticks to make a code block:

    ```ahk
    foo() {
        x := 1
    }
    ```

becomes

```ahk
foo() {
    x := 1
}
```

**Comment by mark-wiemer** [comment]
Referencing #56 since that mentions `return` statement formatting as well
