### ISSUE TITLE
Formatting: indentation added on unquoted v1 string with "for" 

### ISSUE THREAD

**Issue by ewerybody** [mark-wiemer/vscode-autohotkey-plus-plus#40]
Found: Formatting this:
```ahk
InputBox, name, for bla
if somthing
    Return
```
turns to:
```ahk
InputBox, name, for bla
    if somthing
    Return
```
No change expected here.

OK. There you go :) (regarding [#58](https://github.com/AutoHotkey-Plus/vscode-autohotkey/issues/58))
Maybe the formatter should ignore the `for` if there is a keyword in the beginning of the line? 🤔

(still dunno where to look myself. sorry)

**Comment by ewerybody** [comment]
Hey @mark-wiemer! Is that https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/master/src/providers/formattingProvider.ts ? How do I step in there?

**Comment by mark-wiemer** [comment]
Hey @ewerybody, I appreciate your willingness to help. I hope I was able to address your concerns in the [Contributing discussion](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/discussions/42#discussioncomment-345251). If you have further questions, please ask there. But yes, you're on the right track with `formattingProvider.ts` :)
