### ISSUE TITLE
[Suggestion] Add whitespace setting to formatter

### ISSUE THREAD

**Issue by barraIhsan** [mark-wiemer/vscode-autohotkey-plus-plus#49]
So, the default one is 4 spaces. But I love to be able to change it to tabs.
Thanks

**Comment by fade2gray** [comment]
Assuming you are referring to the use of `4 x space` indentation when using the `Format Document` command from the right-click context menu or `Ctrl+Shift+F` - I could stand corrected but I don't think changing the method of indentation used is within the scope of the extension. See the README - [https://github.com/mark-wiemer/vscode-autohotkey-plus-plus#code-format](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus#code-format) (scroll down a little).

Indentation can be toggled between spaces/tabs from the Status Bar, or from the Command Palette `F1` (or `Ctrl_Shift+P`) and type in either `tabs` or `spaces` and choose from the drop-down menu.

**Comment by mark-wiemer** [comment]
I think this is a valid issue with AHK++ (and `cweijan`'s extension) specifically. VS Code usually allows users to format using tabs or spaces, but our formatter ignores that setting and always prints out spaces. We do respsect `tabSize` (e.g. number of spaces to print per indentation level). See [https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/0a8138305a9db7ad4b14008a5ce4595bdeda49cd/src/providers/formattingProvider.ts#L136](formattingProvider.ts:136) for implementation details, will probably be a simple fix once we find out which option corresponds to tabs vs spaces :)
