### ISSUE TITLE
#IfWinActive Directives auto-format issue

### ISSUE THREAD

**Issue by daephx** [mark-wiemer/vscode-autohotkey-plus-plus#55]
Having multiple `#IfWinActive` directives causes the formatter to indent all subsequent directives under the last.

```ahk
#IfWinActive, ahk_exe notepad.exe ; Notepad
    ^w::WinClose
#IfWinActive, ahk_class#32770 ; Windows 10 Properties Panel
    ^w::WinClose
#IfWinActive, ahk_exe taskmgr.exe ; Windows Task Manager
    ^w::WinClose
```

Will format to:

```ahk
#IfWinActive, ahk_exe notepad.exe ; Notepad
    ^w::WinClose
    #IfWinActive, ahk_class#32770 ; Windows 10 Properties Panel
        ^w::WinClose
        #IfWinActive, ahk_exe taskmgr.exe ; Windows Task Manager
            ^w::WinClose
```
Of course, this doesn't make sense because you can't have two windows active at the same time.
Expected behavior: is that this doesn't occur and new directives will maintain their own scope.

**Comment by fade2gray** [comment]
None of the examples in the documentation have the hotkeys indented.

This example from the documentation formats ok ...

```ahk
#IfWinActive Reminders ahk_class #32770  ; The "reminders" window in Outlook.
Enter::Send !o  ; Have an "Enter" keystroke open the selected reminder rather than snoozing it.
#IfWinActive
```

as does this...

```ahk
#IfWinActive, ahk_exe notepad.exe ; Notepad
    ^w::WinClose
#IfWinActive
#IfWinActive, ahk_class#32770 ; Windows 10 Properties Panel
    ^w::WinClose
#IfWinActive
#IfWinActive, ahk_exe taskmgr.exe ; Windows Task Manager
    ^w::WinClose
#IfWinActive
```

¯\\_(ツ)_/¯

**Comment by daephx** [comment]
Good point. I'm not sure on that then if the docs don't reflect the style, however I do think it make things a bit more clear.
Plus the docs don't have indentation for multi-line hotkeys; yet that's still a feature of the formatter.
```ahk
^SPACE::
    msgbox, hello
return
```

The second example you gave does work but seems like a pretty gross way of tricking the formatter to recognize where to stop indenting. Ideally, each `#IfWinActive, ...` in the chain should serve to cut off the one that came before it, rather then turning on some context and turning it back off, just to then turn it back on.
