### ISSUE TITLE
Formatting: function returns don't indent after subroutines

### ISSUE THREAD

**Issue by daephx** [mark-wiemer/vscode-autohotkey-plus-plus#56]
It appears that a function that is defined after a subroutine has this quirk or not having proper indentation when using a return statment.

example:
```ahk

func1(x, y) {
    return x + y
}

Subroutine:
    msgbox, welcome
return

func2(x, y) {
return x * y
}
```

Each statement in these three blocks should indent but the last one does not.
However, it will *if* you remove the subroutine.

Edit:

This also occurs after hotkeys.

```ahk

func1(x, y) {
    return x + y
}

^SPACE::
    msgbox, hello
return

func2(x, y) {
return x * y
}
```

**Comment by fade2gray** [comment]
There are several open and closed issues concerning indentation and formatting that may be worth you looking at.

**Comment by mark-wiemer** [comment]
The formatter is still mostly inherited from `cweijan` and it was designed to always de-indent `return` and `ExitApp` statements. I do not agree with this design, and I do agree with your proposal. Statements in functions, subroutines, and hotkeys should be indented, including the `return` statement. I'll open a discussion to communicate this change.

**Comment by mark-wiemer** [comment]
On second thought, I will simply add this behavior as an optional non-default setting. By default, the formatter will still de-indent `return` statements, but there will be a toggle in the settings to indent `return` statements the same as any other.
