### ISSUE TITLE
use this function for formatting

### ISSUE THREAD

**Issue by FuPeiJiang** [mark-wiemer/vscode-autohotkey-plus-plus#64]
https://github.com/G33kDude/ahkbin/blob/master/www/indent.js

credits
/* Algorithm from maestrith's AHK Studio */
G33kDude

live demo at https://p.ahkscript.org/

perhaps the ahk function starts here: https://github.com/maestrith/AHK-Studio/blob/master/AHK-Studio.ahk#L9567

**Comment by mark-wiemer** [comment]
There might be some good functionality we can extract from this, but parsing a 13000 line file is no easy feat. Additionally, it doesn't seem to format switch case statements correctly, validating my concern that's it's just another regex formatter. A stronger AST-based formatter is ideal, and is what we should work towards if we are going to overhaul the formatting system.

Here is a sample snippet formatted by ahkbin to show the undesirable formatting:

```ahk
switch (k) {
	case 1:
	foo()
	case 2:
	bar()
	default: ExitApp
}

MsgBox % "Hello world"
```

What we want:

```ahk
switch (k) {
	case 1:
	    foo() ; indented one level deeper
	case 2:
	    bar() ; indented one level deeper
	default: ExitApp
}

MsgBox % "Hello world"

**Comment by mark-wiemer** [comment]
Going to close this issue since it's quite broad and I won't be implementing it exactly. If there is functionality you would like to see replicated in the new formatter, open a new issue for each change you'd like
