### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by getupandCROW** [mark-wiemer/vscode-autohotkey-plus-plus#65]
- Issue Type: `Performance`
- Extension Name: `vscode-autohotkey-plus-plus`
- Extension Version: `2.7.2`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.54.1`

attachment:
[mark-wiemer.vscode-autohotkey-plus-plus-unresponsive.cpuprofile.txt](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/files/6105843/mark-wiemer.vscode-autohotkey-plus-plus-unresponsive.cpuprofile.txt)

**Comment by mark-wiemer** [comment]
Related to #9

**Comment by mark-wiemer** [comment]
From version https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/releases/tag/v2.7.2
