### ISSUE TITLE
hotkey (:: should not double indent

### ISSUE THREAD

**Issue by FuPeiJiang** [mark-wiemer/vscode-autohotkey-plus-plus#72]
it's because of the `( LTrim Join` indentation "feature", it doesn't happen in v.2.7.0

### Unformatted input snippet

```autohotkey
(::
foo()
```

### Expected formatted output snippet

```autohotkey
(::
    foo()
```

### Actual formatted output snippet

```autohotkey
(::
        foo()
```

**Comment by mark-wiemer** [comment]
I'm sorry my formatting change introduced new issues. I'm testing against a 3500-line file now to ensure no new issues are introduced. I can definitely make this a toggle this month, it's high-priority since it's an issue that I introduced. Sorry again :(
