### ISSUE TITLE
How to fold code like use 	#pragma region	#pragma endregion ?

### ISSUE THREAD

**Issue by yigexuezha** [mark-wiemer/vscode-autohotkey-plus-plus#79]
How to fold code like use 	#pragma region	#pragma endregion ?

**Comment by fade2gray** [comment]
[https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/77#issuecomment-802812856](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/77#issuecomment-802812856)

**Comment by yigexuezha** [comment]
> [#77 (comment)](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/77#issuecomment-802812856)

thanks！
