### ISSUE TITLE
Run and Debug button is blank after VSCode update

### ISSUE THREAD

**Issue by RaptorX** [mark-wiemer/vscode-autohotkey-plus-plus#88]
Issue Type: <b>Bug</b>

After VSCode update the icon on the top right that is used to run a script now presents a white square.

It happens to other extensions as well

Extension version: 2.8.0
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.45GB (24.24GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Isaias\\Scripts to Work on\\Drip Campaign\\Drip --crash-reporter-id e2f4b83e-b638-4515-902d-f6811bd3e786|
|Screen Reader|no|
|VM|0%|
</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
bridgeflightcf:30299184

```

</details>

**Comment by mark-wiemer** [comment]
OK, this is probably an issue with VS Code itself, not the extension.

On an unrelated note @RaptorX, how did you open this issue? I've set it up to auto-assign myself for all issues created through GitHub, did you create this issue through VS Code itself?

**Comment by RaptorX** [comment]
Yes, this was directly created on the feedback section of VSCode

I thought I was sending the information to the VSCode devs but it seems to be redirected to the Extension dev.
The thing is that I am sure that this is not a problem with the extension.

It started happening after a Code update.

Maybe extensions might need to conform to new standards?

**Comment by mark-wiemer** [comment]
Closing this as resolved thanks to recent updates to VS Code. @RaptorX, feel free to open a discussion if you still have questions about how to modify this project and get it running locally :)
