### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ElectroLund** [mark-wiemer/vscode-autohotkey-plus-plus#9]
- Issue Type: `Performance`
- Extension Name: `vscode-autohotkey-plus-plus`
- Extension Version: `2.5.12`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ROB~1.LUN\AppData\Local\Temp\mark-wiemer.vscode-autohotkey-plus-plus-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mark-wiemer** [comment]
Hi @ElectroLund, thanks for bringing this to my attention. You did forget to upload that file though, all I have access to is a filename, not the file contents. Please upload the file so I can investigate further, thanks.

**Comment by mark-wiemer** [comment]
Closing this issue as it is stale. If you'd like to reopen, please add the file.
