### ISSUE TITLE
Formatting Option Request

### ISSUE THREAD

**Issue by DMDComposer** [mark-wiemer/vscode-autohotkey-plus-plus#94]
**Is your feature request related to a problem? Please describe.**
Formatting pushes all the expressions/variables to be joined together. However, I personally like variables to be all lined up in a column for easy reading like shown below:
![image](https://user-images.githubusercontent.com/53786232/120926453-f4e01c00-c6aa-11eb-886d-9dbecf507502.png)
I even like aligning all the comments too in a column. It would be great if this could be an option or keybind to format comments/operators to be lined up.
**Describe the solution you'd like**
Just an option to be set globally in the settings to ignore operators/variables. 

**Describe alternatives you've considered**
I'm not sure where to look in the parser.json to see if I can manually disable this option? If this isn't an option to be considered to be implemented I would love if someone could help me out and manually disabling it.

Cheers,
DMDComposer

**Comment by mark-wiemer** [comment]
The best suggestion in the short term would be disabling `format on save` for AHK files. I don't foresee extreme difficulties implementing something like this, but it'd probably only support blocks of assignments, it wouldn't transfer over empty lines or comment lines.

Something like this would be the result of formatting with this option:

```ahk
Abc := 1
D   := 2
; comment line here
Ef := 3
G  := 4

Hijk := 5
L    := 6
```
