### ISSUE TITLE
Q: how to configure VS Code launch.json & settings.json

### ISSUE THREAD

**Issue by PackElend** [mark-wiemer/vscode-autohotkey-plus-plus#98]
Hello,
it look like it does not run properly on my machine, can you share settings for launch.json & settings.json
My are:

1.  launch.json
   ```
   {
       // Use IntelliSense to learn about possible attributes.
       // Hover to view descriptions of existing attributes.
       // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
       "version": "0.2.0",
       "configurations": [  
           
       {
           "type": "ahk",
           "request": "launch",
           "name": "AutoHotkey Debugger",
           "program": "",
           "stopOnEntry": true
       }
       ]
   }
   ```

and 

2. settings.json
   ```
    "code-runner.executorMap": {
           ....
            "ahk": "autohotkey",      
           ....
      }
    "files.associations": {
        "*.ahk": "ahk"
    },
    "ahk++.compilePath": "C:/MEINS/TOOLS/AutoHotkey/Compiler/Ahk2Exe.exe",
    "ahk++.executePath": "C:/MEINS/TOOLS/AutoHotkey/AutoHotkeyU64.exe",
    "ahk++.helpPath": "C:/MEINS/TOOLS/AutoHotkey/AutoHotkey.chm"
}
   ```

**Comment by fade2gray** [comment]
> it look like it does not run properly on my machine...

**Comment by PackElend** [comment]
cannot debug anything, so I would like to compare settings

**Comment by fade2gray** [comment]
Never had to create a launch.json or settings.json. What method are you using to launch the debugger?

**Comment by PackElend** [comment]
when I start debug
![image](https://user-images.githubusercontent.com/3542031/128237304-5cf3db0c-dfc4-4564-a663-47ec36a828ab.png)
call stack is empty 
![image](https://user-images.githubusercontent.com/3542031/128237467-09174f4d-f420-4acb-abfc-83f2c600f19b.png)

I can tell that the extension is installed
![image](https://user-images.githubusercontent.com/3542031/128237726-efe549c2-e237-49eb-86bf-5054974b130e.png)

and it calls AutoHotkey
![image](https://user-images.githubusercontent.com/3542031/128237429-652b2cd8-f457-4748-ba81-5aff88bdf3be.png)

**Comment by FuPeiJiang** [comment]
use vscode-autohotkey-debug by zero-plusplus
> Debugging support for AutoHotkey(includes H) v1 and v2

 https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug

**Comment by fade2gray** [comment]
`OutputDebug > If the script's process has no debugger, the system debugger displays the string. If the system debugger is not active, this command has no effect.`
https://www.autohotkey.com/docs/commands/OutputDebug.htm

How about trying a simple
```ahk
text = text
MsgBox, % text
```

**Comment by PackElend** [comment]
> How about trying a simple
> 
> ```ahk
> text = text
> MsgBox, % text
> ```

run script works
![image](https://user-images.githubusercontent.com/3542031/128351101-d3d65ce9-2451-434f-9b36-18eb97f8cca3.png)
debug script seems not to work
![image](https://user-images.githubusercontent.com/3542031/128351419-10fef88a-afbb-4487-b2bb-79ee1078da14.png)

**Comment by fade2gray** [comment]
Not sure what to advise you other than to suggest there could be a conflict with another extension.

Perhaps try disabling all other extensions and just re-enable ahk++, or try the `Start Extension Bisect` from the same menu.

![DisableExts](https://user-images.githubusercontent.com/1332009/128363087-89f14167-999d-4a60-8a9c-42f51bf3052e.png)

**Comment by PackElend** [comment]
back from vacation, have just tried disabling all other, still the same

![image](https://user-images.githubusercontent.com/3542031/129783780-894648ff-c060-4c29-a4ba-549c98c4eef0.png)
![image](https://user-images.githubusercontent.com/3542031/129783987-d0c16120-c383-47d5-9829-49c4e2c91ba6.png)

----

added https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug makes it working but why?

Moreover, I see (now): 
![image](https://user-images.githubusercontent.com/3542031/129785076-87effe99-5885-4e6a-8fcf-739b473dd65e.png)

> This is deprecated, the new recommended way to configure your default shell is by creating a terminal profile in `#terminal.integrated.profiles.windows#` and setting its profile name as the default in `#terminal.integrated.defaultProfile.windows#`. This will currently take priority over the new profiles settings but that will change in the future.

**Comment by fade2gray** [comment]
Maybe this might help - think I remember having to do this myself when I first installed VSCode.

https://stackoverflow.com/questions/67601161/the-new-way-to-configure-default-shell-and-argument-commands-in-vscode

**Comment by PackElend** [comment]
may I ask what you did in regard to AH?
This refers to PowerShell, CMD. Trying to do the right thing for AH would like trial&error for me.

**Comment by mark-wiemer** [comment]
...only 9 months late! Closing this as @PackElend seems to have resolved the issue. Do let me know if there is something else I can help with, but generally your best bet for debug support would be with the debugger suggested in the comments.
