### ISSUE TITLE
Rename AutoHotkey Plus Plus to AutoHotkey++ in Marketplace

### ISSUE THREAD

**Issue by wenfangdu** [mark-wiemer/vscode-autohotkey-plus-plus#99]
The current name looks like a knockoff of the previous ones and feels awkward:

![image](https://user-images.githubusercontent.com/28700378/130885336-2614eb67-04c3-4d82-9c18-8ae16cdffff5.png)

Change it to AutoHotkey++ would be better.

**Comment by mark-wiemer** [comment]
Sorry friends, keeping the name as-is for now. No good reason to change it, honestly. And yes, I wrote "Plus Plus" because it's an extension of "Plus", it only felt natural to keep the wording. I appreciate the suggestion but it's fine as-is
